version: '3'

services:
  react:
    build:
      context: .
    image: scenejs:1.5
    container_name: scene-js
    restart: unless-stopped
    ports:
      - "127.0.0.1:7129:80"
    environment:
      - "TZ=America/Toronto"